CREATE DATABASE job02;
USE job02;
CREATE TABLE etage (id INT AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(255) NOT NULL, numero INT NOT NULL, superficie INT NOT NULL);
DESCRIBE etage;
CREATE TABLE salle (id INT AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(255) NOT NULL, id_etage INT NOT NULL, capacite INT NOT NULL);
DESCRIBE salle;